### ISSUE TITLE
Error when start wikiclass

### ISSUE THREAD

**Issue by vinhqdang** [wiki-ai/wikiclass#11]
Hello all

I am using Mac OS 10.10, python 3.5.0.

I tried:

pip3 install wikiclass

Then:

python3
>>>import wikiclass
...
ImportError: No module named 'mwparserfromhell'

So, I installed module 'mwparserfromhell' by "pip3 install".
Then try again

python3
>>>import wikiclass
...
ImportError: No module named 'mw'

That time, I tried to install module 'mw' but not success

pip3 install mw
>>>Collecting mw
>>>  Could not find a version that satisfies the requirement mw (from versions: )
>>>No matching distribution found for mw

How can I fix this problem?

**Comment by vinhqdang** [comment]
I found the problem, I should install the module 'mediawiki-utilities'

https://pypi.python.org/pypi/mediawiki-utilities/0.2.1

And now I met another problem, reported that module 'docopt' no exist. OMG

**Comment by vinhqdang** [comment]
In the end, I need to install the following packages (through **pip3 install package_name** command)

- mwparserfromhell
- mediawiki-utilities
- docopt
- gfortran (through 'brew install gcc'), to install scipy, for revscroting 
- revscoring

**Comment by vinhqdang** [comment]
The last error I met is the module 'mwtypes.files' does not exist, even the module 'mwtypes' already installed.

**Comment by halfak** [comment]
Thanks for reporting.  It looks like there was an issue with the requirements.txt being loaded, but as a generator -- not a list.  I've just pushed a change to fix that.  See https://github.com/wiki-ai/wikiclass/commit/845e0984010ee0dbadd1230b00d4fdff27ae3e59

I'll be pushing a new version to pypi shortly.  I'll ping here when that is ready.   Thanks for your patience.

**Comment by halfak** [comment]
OK.  Should be good.  `pip install wikiclass --upgrade` should pull down 0.1.2.

**Comment by vinhqdang** [comment]
It fixed the problem, thanks
